name: Post link of the week

on:
  workflow_dispatch:
  schedule:
    - cron: "55 20 * * 1,3,5"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Mastodon.py

    - name: Generate and post Link of the Week
      env: # Or as an environment variable
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: python lotw.py
      
    - name: Commit changes to list
      run: |
        git add sitecat.txt
        git commit -m "[LOTW] $(date)"
        git push origin master
