name: Post throwback link (if any)

on:
  workflow_dispatch:
  schedule:
    - cron: "55 17 * * *"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Mastodon.py

    - name: Generate and post Throwback link
      env: # Or as an environment variable
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: python lotw.py throwback
